apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-behov-pdf-generator
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: {{ kafka_pool }}
  replicas:
    min: 3
    max: 6
  resources:
    limits:
      memory:  2000Mi
    requests:
      cpu: 200m
      memory: 1000Mi
  secureLogs:
    enabled: true
  ingresses:
    - {{ ingress }}
  env:
    - name: DP_MELLOMLAGRING_API_SCOPE
      value: {{ dp_mellomlagring_api_scope }}
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: dp-rapportering
    outbound:
      rules:
        - application: dp-mellomlagring
