apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-behov-pdf-generator
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: {{ kafka_pool }}
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 256Mi
  secureLogs:
    enabled: true
  env:
    - name: DP_MELLOMLAGRING_API_SCOPE
      value: {{ dp_mellomlagring_api_scope }}
