apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-behov-pdf-generator
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: "{{ image }}"
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: "{{ kafka_pool }}"
  replicas:
    min: 3
    max: 6
  resources:
    limits:
      memory: 6144Mi
    requests:
      cpu: 50m
      memory: 512Mi
  env:
    # Ganske unik minne tuning for denne appen. Den trenger mye minne i korte perioder.
    # 25% av 6144 = 1536Mi tilgjengelig for heap.
    # InitiatingHeapOccupancyPercent = 25% betyr at GC starter når 25% av heap er brukt.
    # 25% av 1536 = 384Mi. Det betyr at appen bør ligge på rundt 384Mi ved vanlig drift.
    - name: JDK_JAVA_OPTIONS
      value: >-
        -XX:+UseParallelGC
        -XX:ActiveProcessorCount=4
        -XX:MaxRAMPercentage=25.0
        -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9999
        -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
        -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=localhost
        -Dcom.sun.management.jmxremote.rmi.port=9999
    - name: DP_MELLOMLAGRING_API_SCOPE
      value: "{{ dp_mellomlagring_api_scope }}"
  secureLogs:
    enabled: true
  ingresses:
    - {{ ingress }}
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: dp-rapportering
        - application: dp-melding-om-vedtak
    outbound:
      rules:
        - application: dp-mellomlagring
        - application: logging
          namespace: nais-system
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudprofiler.agent
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: java
