apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-behov-pdf-generator
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: {{ kafka_pool }}
  replicas:
    min: 3
    max: 6
  resources:
    limits:
      memory: 6144Mi
    requests:
      cpu: 50m
      memory: 512Mi
  env:
    # Ganske unik minne tuning for denne appen. Den trenger mye minne i korte perioder.
    # 25% av 6144 = 1536Mi tilgjengelig for heap.
    # InitiatingHeapOccupancyPercent = 25% betyr at GC starter når 25% av heap er brukt.
    # 25% av 1536 = 384Mi. Det betyr at appen bør ligge på rundt 384Mi ved vanlig drift.
    - name: JDK_JAVA_OPTIONS
      value: -XX:+UseParallelGC -XX:ActiveProcessorCount=4 -XX:InitiatingHeapOccupancyPercent=25 -XX:MaxRAMPercentage=25.0
    - name: DP_MELLOMLAGRING_API_SCOPE
      value: {{ dp_mellomlagring_api_scope }}
    - name: JAVA_OPTS
      value: -agentpath:/opt/cprof/profiler_java_agent.so=-cprof_service=dp-behov-pdf-generator,-cprof_enable_heap_sampling=true,-logtostderr,-minloglevel=0,-cprof_project_id=teamdagpenger-prod-9042
  secureLogs:
    enabled: true
  ingresses:
    - {{ ingress }}
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: dp-rapportering
    outbound:
      rules:
        - application: dp-mellomlagring
